name: XWAL

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.x"
      - name: Install dependencies
        run: make tidy
      - name: Build
        run: make build

  test:
    strategy:
      matrix:
        go-version: [1.20.x, 1.21.x, 1.22.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: make tidy
      - name: Run tests
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - run: make test
