name: xWAL Release

on:
  push:
    tags:
      - "*" # triggers only if a new tag is pushed

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release xWAL library versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goreleaser/goreleaser-action@v5
        with:
          args: release --config .goreleaser.yaml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
